config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(strong_params(params))
		if @article.save
			flash[:notice] = "Article successfully created"
			redirect_to article_path(@article)
		else
			render "new"
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update strong_params(params)
			flash[:notice] = "Article Successfully updated"
			redirect_to article_path(@article)
		else
			render "edit"
		end
	end

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:notice] = "Article Was Successfully Deleted"
		redirect_to articles_path
	end

	private
	def strong_params(params)
		params.require(:article).permit(:title, :description);
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit the article</h1>

<%= form_for @article do |f| %>
	<%= f.label :title, "Enter Title Here" %><br>
	<%= f.text_field :title %><br>
	<%= f.label :description, "Enter Description Here" %><br>
	<%= f.text_area :description %><br>
	<%= f.submit "Done" %>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<table>
	<tr>
		<th>ID</th>
		<th>Title</th>
		<th>Description</th>
		<th>Created At</th>
		<th>Updated At</th>
	</tr>
	<% @articles.each do |article| %>
		<tr>
			<td><%= article.id %></td>
			<td><%= article.title %></td>
			<td><%= article.description %></td>
			<td><%= article.created_at %></td>
			<td><%= article.updated_at %></td>
			<td><%= link_to "Show", article_path(article)%></td>
			<td><%= link_to "Edit", edit_article_path(article)%></td>
			<td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}%></td>
		</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1>This is where you create a new article</h1>

<% if @article.errors.any? %>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @article do |f| %>
	<%= f.label :title, "Enter title here"%><br>
	<%= f.text_field :title %><br>
	<%= f.label :description, "Enter description here"%><br>
	<%= f.text_area :description %><br>
	<%= f.submit "Done" %>
<% end %>

app/views/articles/show.html.erb
<h1>Here is the article content</h1>

<p>
	Title:
	<%= @article.title %>
</p>

<p>
	Description:
	<%= @article.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if !flash.empty? %>
  <ul>
  	<% flash.each do |k, v| %>
  		<li><%= v %></li>
  	<% end %>
  </ul>
<% end %>
<%= yield %>

</body>
</html>